version: '3'
services: 
  server: 
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment: 
      - PORT=8080
      - SECRET=qwert228
      - DB_HOST=postgres

  postgres:
    image: postgres:11.2-alpine
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
